include:
  - path:
    - services/vectordb/docker-compose.yaml
    # - services/nim-ms/docker-compose.yaml
    - services/reranking/docker-compose.yaml

services:
  chain-server:
    container_name: chain-server
    image: chain-server:${TAG:-latest}
    build:
      # Set context to root directory
      context: .
      dockerfile: services/chain_server/Dockerfile
      args:
        # Build args, used to copy relevant directory inside the container relative to root
        EXAMPLE_PATH: '.'
    volumes:
      - /static-data/team_08/prompt.yaml:/prompt.yaml
    # start the server on port 8081
    command: --port 8081 --host 0.0.0.0
    environment:
      # Path to example directory relative to root
      EXAMPLE_PATH: '.'
      # URL on which vectorstore is hosted
      APP_VECTORSTORE_URL: "http://milvus:19530"
      # Type of vectordb used to store embedding supported type milvus, pgvector
      APP_VECTORSTORE_NAME: "milvus"
      # url on which llm model is hosted. For local NIM deployment
      APP_LLM_MODELNAME: ${APP_LLM_MODELNAME:-"meta/llama3-8b-instruct"}
      # embedding model engine used for inference, using local NIM
      APP_LLM_MODELENGINE: nvidia-ai-endpoints
      APP_LLM_SERVERURL: ${APP_LLM_SERVERURL:-"http://nemollm-inference:8000/v1"}
      APP_EMBEDDINGS_MODELNAME: ${APP_EMBEDDINGS_MODELNAME:-"nvidia/nv-embedqa-e5-v5"}
      # embedding model engine used for inference, using local NIM
      APP_EMBEDDINGS_MODELENGINE: ${APP_EMBEDDINGS_MODELENGINE:-nvidia-ai-endpoints}
      # url on which embedding model is hosted. For local NIM deployment
      APP_EMBEDDINGS_SERVERURL: ${APP_EMBEDDINGS_SERVERURL:-"http://nemollm-embedding:8000/v1"}
      # text splitter model name, it's fetched from huggingface
      APP_TEXTSPLITTER_MODELNAME: Snowflake/snowflake-arctic-embed-l
      APP_TEXTSPLITTER_CHUNKSIZE: 506
      APP_TEXTSPLITTER_CHUNKOVERLAP: 200
      NVIDIA_API_KEY: ${NVIDIA_API_KEY}
      # vectorstore collection name to store embeddings 
      COLLECTION_NAME: ${COLLECTION_NAME:-nvidia_api_catalog}
      APP_RETRIEVER_TOPK: 4
      APP_RETRIEVER_SCORETHRESHOLD: 0.25
      # ranking model configuration for reranking
      APP_RANKING_MODELNAME: ${APP_RANKING_MODELNAME}
      APP_RANKING_MODELENGINE: ${APP_RANKING_MODELENGINE}
      APP_RANKING_SERVERURL: ${APP_RANKING_SERVERURL}
      # observability server url
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      # enable observability in chain server
      ENABLE_TRACING: false
      # Log level for server, supported level NOTSET, DEBUG, INFO, WARN, ERROR, CRITICAL
      LOGLEVEL: ${LOGLEVEL:-INFO}
    ports:
    - "8081:8081"
    expose:
    - "8081"
    shm_size: 5gb
    depends_on:
      # nemollm-embedding:
      #   condition: service_healthy
      #   required: false
      # nemollm-inference:
      #   condition: service_healthy
      #   required: false
      reranking:
        condition: service_healthy
        required: false

  rag-playground:
    container_name: rag-playground
    image: rag-playground:${TAG:-latest}
    build:
      # Set context to rag_playground directory
      context: services/rag_playground/
      dockerfile: Dockerfile
      args:
        # select UI type, supported model default, speech
        PLAYGROUND_MODE: ${PLAYGROUND_MODE:-default}
    command: --port 8090
    environment:
      # URL or chain server container
      APP_SERVERURL: http://chain-server
      APP_SERVERPORT: 8081
      # model name displayed on UI
      APP_MODELNAME: ${APP_LLM_MODELNAME:-"meta/llama3-70b-instruct"}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      # enable observability in rag playground
      ENABLE_TRACING: false
    volumes:
      - /static-data/team_08/swtbot-example:/swtbot-example
    ports:
    - "8090:8090"
    expose:
    - "8090"
    depends_on:
    - chain-server

networks:
  default:
    name: nvidia-rag
